server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ['.*']
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'service'
        regex: '(.+)'
        replacement: '${1}'

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # Application logs
  - job_name: applications
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          __path__: /var/log/apps/*.log

pipeline_stages:
  - json:
      expressions:
        level: level
        message: message
        timestamp: timestamp
        service: service
        method: method
        url: url
        statusCode: statusCode
        error: error
        stack: stack
